#!/bin/bash

#Installation des outils de développement
# get cards.devel

# Les fichiers de configuration
# /etc/cards.conf
cat >/etc/cards.conf << EOF
dir /usr/ports/perso
dir /usr/ports/gui
dir /usr/ports/cli
dir /usr/ports/base
logdir /var/log/pkgbuild
base /usr/ports/base
EOF

# Les fichiers de configuration
# /etc/pkgmk.conf
cat > /etc/pkgmk.conf << EOF
export CFLAGS="-O2 -pipe"
export CXXFLAGS="\${CFLAGS}"
case \${PKGMK_ARCH} in
    "x86_64"|"")
       export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
       ;;
    "i686")
       export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
       export CFLAGS="${CFLAGS} -m32"
       export CXXFLAGS="${CXXFLAGS} -m32"
       export LDFLAGS="${LDFLAGS} -m32"
       ;;
    *)
       echo "Unknown architecture selected! Exiting."
       exit 1
       ;;
esac
PKGMK_SOURCE_DIR="/tmp"
PKGMK_KEEP_SOURCES="yes"
PKGMK_WORK_DIR="/tmp/work"
PKGMK_IGNORE_REPO="no"
PKGMK_IGNORE_COLLECTION="no"
PKGMK_GROUPS=()
PKGMK_LOCALES=()
PKGMK_COMPRESS_PACKAGE="yes"
PKGMK_COMPRESSION_MODE="xz"
PKGMK_CLEAN="no"
PKGMK_IGNORE_RUNTIMEDEPS="no"
EOF


echo "******************************************"
echo " Synchronisation des binaires via rsync : "
echo " Pour quitter   ==========> taper 1 : "
echo " Branche FIXED  ==========> taper 2 : "
echo " Branche ROLLING === =====> taper 3 : "
echo "******************************************"
read -p" Taper votre choix : 1 - 2 ou 3 : " choix
echo "******************************************"

# Abandon de la commande
if [ $choix = "1" ]
  then
   exit
elif [ $choix = "2" ]
  then
  
  # Version fixed 
  echo " **********************************************"
  echo " Vous avez choisi d'installer une version FIXED"
  echo " Si ce n'est pas le cas faites Ctrl + C"
  echo " Si c'est votre choix, tapez Entrée :"
  read -p"***********************************************"
  # Créer le dossier racine  
  mkdir /usr/ports/perso
  
  # Synchronisation des binaires via rsync
  # La branche fixed
  #
  for i in base cli gui
   do
     rsync -avz --delete-after rsync://downloads.nutyx.org/nutyx/`uname -m`/fixed/$i/ \
   /usr/ports/$i/
  done
  
elif [ $choix = "3" ]
  then  
    	
  # Version rolling
  echo " ***************************************************"
  echo " Vous avez choisi d'installer la version ROLLING"
  echo " Si ce n'est pas le cas faites Ctrl + C"
  echo " Si c'est votre choix, tapez Entrée :"
  read -p"***********************************************"
  # Créer le dossie racine  
  mkdir /usr/ports/perso
  
  # Synchronisation des binaires via rsync
  # La branche rolling 
  #
  for i in base cli gui
   do
     rsync -avz --delete-after rsync://downloads.nutyx.org/nutyx/`uname -m`/rolling/$i/ \
   /usr/ports/$i/
  done

else
        
  echo " **********************************************"
  echo " Votre saisie ne correspond à aucun des choix  "
  echo " Appyez sur Entrée et recommencez"
  read -p "***********************************************"
  exit
fi
exit 0

# Retour a la machine hote


